;; (require 'helm)
;; (require 'helm-config)
;; (setq helm-M-x-fuzzy-match t)
;; (setq helm-buffers-fuzzy-matching t)
;; (setq helm-recentf-fuzzy-matching t)
;; (setq helm-split-window-in-side-p t)

;; (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
;; (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
;; (define-key helm-map (kbd "C-z") 'helm-select-action)
;; (global-set-key (kbd "C-x m") 'helm-mini)
;; (global-set-key (kbd "C-x b") 'helm-buffers-list)
;; (global-set-key (kbd "C-x C-f") 'helm-find-files)
;; (global-set-key (kbd "C-x C-m") 'helm-M-x)
;; (global-set-key (kbd "C-x C-h") 'helm-apropos)
;; (global-set-key (kbd "C-x p") 'helm-projectile-find-file)
;; (global-set-key (kbd "C-x C-p") 'helm-projectile-switch-project)
;; (global-set-key (kbd "C-x f") 'helm-occur)

